// InsightForge – 20 System Report Definitions
// Pre-built reports for common analytics use cases

import type { ReportDefinition } from '@/lib/query-engine/types'

// Placeholder data source IDs – replaced at seed time with real UUIDs
export const DEMO_SOURCE_ID = 'demo-postgresql-source'
export const REST_SOURCE_ID = 'demo-rest-source'

export const SYSTEM_REPORTS: ReportDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. Work Orders by Status
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-001',
    name: 'Work Orders by Status',
    description: 'Grouped bar chart showing work order counts broken down by current status.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'status',
        label: 'Status',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'id',
        label: 'Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [],
    sorts: [{ fieldId: 'f2', field: 'id', direction: 'desc', priority: 1 }],
    chartConfig: {
      type: 'bar',
      xAxisField: 'status',
      yAxisFields: ['id'],
      orientation: 'vertical',
      showLegend: true,
      showDataLabels: true,
      colors: ['#7c3aed', '#a78bfa', '#ddd6fe'],
    },
    cacheSeconds: 300,
  },

  // ─────────────────────────────────────────────────────────────
  // 2. SLA Compliance Rate – KPI Scorecard with trend
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-002',
    name: 'SLA Compliance Rate',
    description: 'KPI card showing overall SLA compliance percentage with 30-day trend sparkline.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'resolved_at',
        label: 'Date',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        dateGranularity: 'day',
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'sla_met',
        label: 'SLA Compliance %',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.0%',
        isCalculated: true,
        formula: 'AVG(CASE WHEN sla_met = true THEN 1.0 ELSE 0.0 END) * 100',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f1',
        field: 'resolved_at',
        operator: 'gte',
        value: '{{__30d_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f1', field: 'resolved_at', direction: 'asc', priority: 1 }],
    chartConfig: {
      type: 'gauge',
      gaugeMin: 0,
      gaugeMax: 100,
      gaugeBands: [
        { min: 0, max: 70, color: '#ef4444', label: 'Poor' },
        { min: 70, max: 90, color: '#f59e0b', label: 'Acceptable' },
        { min: 90, max: 100, color: '#22c55e', label: 'Excellent' },
      ],
      sparklineField: 'sla_met',
      trendField: 'resolved_at',
      kpiSize: 'large',
      colorThresholds: [
        { value: 90, color: 'green', operator: '>=' },
        { value: 70, color: 'amber', operator: '>=' },
        { value: 0, color: 'red', operator: '>=' },
      ],
    },
    cacheSeconds: 600,
  },

  // ─────────────────────────────────────────────────────────────
  // 3. Work Orders by Site – Horizontal Bar
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-003',
    name: 'Work Orders by Site',
    description: 'Horizontal bar chart comparing work order volume across different sites.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'sites',
        columnName: 'name',
        label: 'Site',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'id',
        label: 'Work Orders',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [],
    sorts: [{ fieldId: 'f2', field: 'id', direction: 'desc', priority: 1 }],
    limit: 20,
    chartConfig: {
      type: 'bar',
      xAxisField: 'id',
      yAxisFields: ['name'],
      orientation: 'horizontal',
      showDataLabels: true,
      showLegend: false,
      colors: ['#7c3aed'],
    },
    cacheSeconds: 300,
  },

  // ─────────────────────────────────────────────────────────────
  // 4. Monthly Work Order Volume – Line Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-004',
    name: 'Monthly Work Order Volume',
    description: 'Line chart tracking total work order volume by month over the last 12 months.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'created_at',
        label: 'Month',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        dateGranularity: 'month',
        format: 'MMM yyyy',
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'id',
        label: 'Work Orders',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f1',
        field: 'created_at',
        operator: 'gte',
        value: '{{__12m_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f1', field: 'created_at', direction: 'asc', priority: 1 }],
    chartConfig: {
      type: 'line',
      xAxisField: 'created_at',
      yAxisFields: ['id'],
      smooth: true,
      fillArea: true,
      showLegend: false,
      showDataLabels: false,
      comparisonEnabled: true,
      comparisonPeriod: 'prior_year',
      colors: ['#7c3aed', '#a78bfa'],
    },
    cacheSeconds: 900,
  },

  // ─────────────────────────────────────────────────────────────
  // 5. Technician Performance – Data Table
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-005',
    name: 'Technician Performance',
    description: 'Table showing each technician\'s completed work orders, average resolution time, and SLA compliance rate.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'technicians',
        columnName: 'name',
        label: 'Technician',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'id',
        label: 'Completed WOs',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'resolution_time_hours',
        label: 'Avg Resolution (hrs)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.1',
      },
      {
        id: 'f4',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'sla_met',
        label: 'SLA Compliance %',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.0%',
        isCalculated: true,
        formula: 'AVG(CASE WHEN sla_met = true THEN 100.0 ELSE 0.0 END)',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f_status',
        field: 'status',
        operator: 'eq',
        value: 'completed',
        type: 'string',
      },
    ],
    sorts: [{ fieldId: 'f4', field: 'sla_met', direction: 'desc', priority: 1 }],
    cacheSeconds: 300,
  },

  // ─────────────────────────────────────────────────────────────
  // 6. Open vs Closed Tickets – Donut Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-006',
    name: 'Open vs Closed Tickets',
    description: 'Donut chart comparing currently open tickets to closed tickets.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'state',
        label: 'State',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'id',
        label: 'Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [],
    sorts: [],
    chartConfig: {
      type: 'donut',
      donutInnerRadius: 60,
      labelFormat: 'both',
      showLegend: true,
      legendPosition: 'bottom',
      colors: ['#ef4444', '#22c55e', '#f59e0b', '#3b82f6'],
    },
    cacheSeconds: 120,
  },

  // ─────────────────────────────────────────────────────────────
  // 7. Priority Distribution – Pie Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-007',
    name: 'Priority Distribution',
    description: 'Pie chart showing breakdown of tickets/work orders by priority level.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'priority',
        label: 'Priority',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'id',
        label: 'Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [],
    sorts: [{ fieldId: 'f2', field: 'id', direction: 'desc', priority: 1 }],
    chartConfig: {
      type: 'pie',
      labelFormat: 'both',
      showLegend: true,
      legendPosition: 'right',
      minSlicePercent: 2,
      colors: ['#ef4444', '#f97316', '#f59e0b', '#22c55e'],
    },
    cacheSeconds: 300,
  },

  // ─────────────────────────────────────────────────────────────
  // 8. Ticket Resolution Time – Box Plot by Category
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-008',
    name: 'Ticket Resolution Time',
    description: 'Distribution of ticket resolution time (hours) by category using statistical summary.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'category',
        label: 'Category',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'resolution_time_hours',
        label: 'Min Resolution (hrs)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'min',
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'resolution_time_hours',
        label: 'Avg Resolution (hrs)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.1',
      },
      {
        id: 'f4',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'resolution_time_hours',
        label: 'Max Resolution (hrs)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'max',
      },
      {
        id: 'f5',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'tickets',
        columnName: 'resolution_time_hours',
        label: 'Median Resolution (hrs)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'median',
        format: '0.1',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f_state',
        field: 'state',
        operator: 'eq',
        value: 'closed',
        type: 'string',
      },
    ],
    sorts: [{ fieldId: 'f3', field: 'resolution_time_hours', direction: 'desc', priority: 1 }],
    cacheSeconds: 600,
  },

  // ─────────────────────────────────────────────────────────────
  // 9. Access Events by Hour – Heatmap (hour × day)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-009',
    name: 'Access Events by Hour',
    description: 'Heatmap showing access event density by hour of day and day of week.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'access_events',
        columnName: 'day_of_week',
        label: 'Day of Week',
        type: 'string',
        isDimension: true,
        isMeasure: false,
        isCalculated: true,
        formula: "TO_CHAR(timestamp, 'Day')",
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'access_events',
        columnName: 'hour_of_day',
        label: 'Hour of Day',
        type: 'number',
        isDimension: true,
        isMeasure: false,
        isCalculated: true,
        formula: 'EXTRACT(HOUR FROM timestamp)',
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'access_events',
        columnName: 'id',
        label: 'Event Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f_ts',
        field: 'timestamp',
        operator: 'gte',
        value: '{{__30d_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [],
    chartConfig: {
      type: 'heatmap',
      heatmapXField: 'hour_of_day',
      heatmapYField: 'day_of_week',
      heatmapValueField: 'id',
      showLegend: true,
      colors: ['#ede9fe', '#7c3aed'],
    },
    cacheSeconds: 900,
  },

  // ─────────────────────────────────────────────────────────────
  // 10. Power Consumption Trends – Stacked Area Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-010',
    name: 'Power Consumption Trends',
    description: 'Stacked area chart of power consumption (kW) by zone over time.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'power_metrics',
        columnName: 'timestamp',
        label: 'Date',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        dateGranularity: 'day',
        format: 'MMM d',
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'power_metrics',
        columnName: 'zone',
        label: 'Zone',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'power_metrics',
        columnName: 'kw_consumed',
        label: 'kW Consumed',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'sum',
        format: '0,0.0',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f1',
        field: 'timestamp',
        operator: 'gte',
        value: '{{__30d_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f1', field: 'timestamp', direction: 'asc', priority: 1 }],
    chartConfig: {
      type: 'area',
      xAxisField: 'timestamp',
      yAxisFields: ['kw_consumed'],
      groupByField: 'zone',
      stack: true,
      stackMode: 'normal',
      smooth: true,
      fillArea: true,
      showLegend: true,
      legendPosition: 'bottom',
      colors: ['#7c3aed', '#a78bfa', '#c4b5fd', '#ddd6fe', '#ede9fe'],
    },
    cacheSeconds: 600,
  },

  // ─────────────────────────────────────────────────────────────
  // 11. Top 10 Assets by Incidents – Horizontal Bar (limit 10)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-011',
    name: 'Top 10 Assets by Incidents',
    description: 'Horizontal bar chart showing the 10 assets with the most reported incidents.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'assets',
        columnName: 'name',
        label: 'Asset',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'incidents',
        columnName: 'id',
        label: 'Incident Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [],
    sorts: [{ fieldId: 'f2', field: 'id', direction: 'desc', priority: 1 }],
    limit: 10,
    chartConfig: {
      type: 'bar',
      xAxisField: 'id',
      yAxisFields: ['name'],
      orientation: 'horizontal',
      showDataLabels: true,
      showLegend: false,
      colors: ['#ef4444'],
    },
    cacheSeconds: 600,
  },

  // ─────────────────────────────────────────────────────────────
  // 12. Visitor Log Summary – Data Table
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-012',
    name: 'Visitor Log Summary',
    description: 'Data table of visitor entries with host, entry/exit times, and duration.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'visitor_logs',
        columnName: 'visitor_name',
        label: 'Visitor',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'visitor_logs',
        columnName: 'host',
        label: 'Host',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'visitor_logs',
        columnName: 'site_id',
        label: 'Site',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f4',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'visitor_logs',
        columnName: 'entry_time',
        label: 'Entry Time',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        format: 'MMM d, HH:mm',
      },
      {
        id: 'f5',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'visitor_logs',
        columnName: 'exit_time',
        label: 'Exit Time',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        format: 'HH:mm',
      },
      {
        id: 'f6',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'visitor_logs',
        columnName: 'duration_minutes',
        label: 'Duration (min)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        isCalculated: true,
        formula: 'EXTRACT(EPOCH FROM (exit_time - entry_time)) / 60',
        format: '0',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f4',
        field: 'entry_time',
        operator: 'gte',
        value: '{{__7d_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f4', field: 'entry_time', direction: 'desc', priority: 1 }],
    limit: 100,
    cacheSeconds: 60,
  },

  // ─────────────────────────────────────────────────────────────
  // 13. Billing Summary by Tenant – Data Table with Totals
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-013',
    name: 'Billing Summary by Tenant',
    description: 'Billing amounts per tenant for the current period with payment status.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'billing',
        columnName: 'tenant_id',
        label: 'Tenant',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'billing',
        columnName: 'period',
        label: 'Period',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'billing',
        columnName: 'amount',
        label: 'Amount (AED)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'sum',
        format: '$0,0.00',
      },
      {
        id: 'f4',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'billing',
        columnName: 'due_date',
        label: 'Due Date',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        format: 'MMM d, yyyy',
      },
      {
        id: 'f5',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'billing',
        columnName: 'status',
        label: 'Status',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f2',
        field: 'period',
        operator: 'eq',
        value: '{{__current_period}}',
        type: 'string',
        allowDashboardOverride: true,
        parameterName: 'billing_period',
      },
    ],
    sorts: [{ fieldId: 'f3', field: 'amount', direction: 'desc', priority: 1 }],
    cacheSeconds: 3600,
  },

  // ─────────────────────────────────────────────────────────────
  // 14. Alert Volume by Severity – Bar + Line Combo
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-014',
    name: 'Alert Volume by Severity',
    description: 'Combo chart: bars for alert count by severity, line for cumulative total over time.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'alerts',
        columnName: 'created_at',
        label: 'Date',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        dateGranularity: 'day',
        format: 'MMM d',
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'alerts',
        columnName: 'severity',
        label: 'Severity',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'alerts',
        columnName: 'id',
        label: 'Alert Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f1',
        field: 'created_at',
        operator: 'gte',
        value: '{{__30d_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f1', field: 'created_at', direction: 'asc', priority: 1 }],
    chartConfig: {
      type: 'bar',
      xAxisField: 'created_at',
      yAxisFields: ['id'],
      groupByField: 'severity',
      stack: true,
      secondaryYAxis: true,
      showLegend: true,
      colors: ['#ef4444', '#f97316', '#f59e0b', '#3b82f6'],
    },
    cacheSeconds: 300,
  },

  // ─────────────────────────────────────────────────────────────
  // 15. Asset Uptime Dashboard – Gauge Charts
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-015',
    name: 'Asset Uptime Dashboard',
    description: 'Gauge charts showing uptime percentage for critical assets.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'assets',
        columnName: 'name',
        label: 'Asset',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'assets',
        columnName: 'uptime_pct',
        label: 'Uptime %',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.0%',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f_critical',
        field: 'is_critical',
        operator: 'eq',
        value: true,
        type: 'boolean',
      },
    ],
    sorts: [{ fieldId: 'f2', field: 'uptime_pct', direction: 'asc', priority: 1 }],
    limit: 12,
    chartConfig: {
      type: 'gauge',
      gaugeMin: 0,
      gaugeMax: 100,
      gaugeBands: [
        { min: 0, max: 90, color: '#ef4444', label: 'Critical' },
        { min: 90, max: 99, color: '#f59e0b', label: 'Warning' },
        { min: 99, max: 100, color: '#22c55e', label: 'Healthy' },
      ],
      kpiSize: 'small',
    },
    cacheSeconds: 300,
  },

  // ─────────────────────────────────────────────────────────────
  // 16. Maintenance Cost by Category – Treemap
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-016',
    name: 'Maintenance Cost by Category',
    description: 'Treemap showing maintenance spend proportionally distributed across categories.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'category',
        label: 'Category',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'total_cost',
        label: 'Total Cost (AED)',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'sum',
        format: '$0,0',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f_date',
        field: 'created_at',
        operator: 'gte',
        value: '{{__12m_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f2', field: 'total_cost', direction: 'desc', priority: 1 }],
    chartConfig: {
      type: 'treemap',
      showDataLabels: true,
      showLegend: false,
      colors: ['#7c3aed', '#6d28d9', '#5b21b6', '#4c1d95', '#3b0764'],
    },
    cacheSeconds: 3600,
  },

  // ─────────────────────────────────────────────────────────────
  // 17. Incident Response Funnel – Funnel Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-017',
    name: 'Incident Response Funnel',
    description: 'Funnel chart showing how incidents move through the response lifecycle stages.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'incidents',
        columnName: 'stage',
        label: 'Stage',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'incidents',
        columnName: 'id',
        label: 'Count',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
      },
    ],
    filters: [],
    sorts: [{ fieldId: 'f2', field: 'id', direction: 'desc', priority: 1 }],
    chartConfig: {
      type: 'funnel',
      labelFormat: 'both',
      showLegend: false,
      colors: ['#7c3aed', '#8b5cf6', '#a78bfa', '#c4b5fd', '#ddd6fe'],
    },
    cacheSeconds: 600,
  },

  // ─────────────────────────────────────────────────────────────
  // 18. Team Workload Distribution – Radar Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-018',
    name: 'Team Workload Distribution',
    description: 'Radar chart comparing multiple metrics across teams: open tickets, completions, avg priority, SLA compliance.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'teams',
        columnName: 'name',
        label: 'Team',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'open_count',
        label: 'Open WOs',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
        isCalculated: true,
        formula: "COUNT(CASE WHEN status = 'open' THEN 1 END)",
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'completed_count',
        label: 'Completed WOs',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
        isCalculated: true,
        formula: "COUNT(CASE WHEN status = 'completed' THEN 1 END)",
      },
      {
        id: 'f4',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'work_orders',
        columnName: 'sla_compliance',
        label: 'SLA Compliance',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        isCalculated: true,
        formula: 'AVG(CASE WHEN sla_met = true THEN 100.0 ELSE 0.0 END)',
      },
    ],
    filters: [],
    sorts: [{ fieldId: 'f3', field: 'completed_count', direction: 'desc', priority: 1 }],
    chartConfig: {
      type: 'radar',
      radarIndicators: ['open_count', 'completed_count', 'sla_compliance'],
      showLegend: true,
      legendPosition: 'bottom',
      colors: ['#7c3aed', '#22c55e', '#f59e0b'],
    },
    cacheSeconds: 600,
  },

  // ─────────────────────────────────────────────────────────────
  // 19. Safety Violations Over Time – Waterfall Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-019',
    name: 'Safety Violations Over Time',
    description: 'Waterfall chart illustrating cumulative safety violations and resolutions month over month.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'safety_incidents',
        columnName: 'occurred_at',
        label: 'Month',
        type: 'date',
        isDimension: true,
        isMeasure: false,
        dateGranularity: 'month',
        format: 'MMM yyyy',
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'safety_incidents',
        columnName: 'new_violations',
        label: 'New Violations',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
        isCalculated: true,
        formula: "COUNT(CASE WHEN type = 'violation' THEN 1 END)",
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'safety_incidents',
        columnName: 'resolved_violations',
        label: 'Resolved',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'count',
        isCalculated: true,
        formula: "COUNT(CASE WHEN status = 'resolved' THEN 1 END)",
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f1',
        field: 'occurred_at',
        operator: 'gte',
        value: '{{__12m_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f1', field: 'occurred_at', direction: 'asc', priority: 1 }],
    chartConfig: {
      type: 'bar',
      xAxisField: 'occurred_at',
      yAxisFields: ['new_violations', 'resolved_violations'],
      showLegend: true,
      legendPosition: 'top',
      colors: ['#ef4444', '#22c55e'],
      waterfallStartField: 'new_violations',
      waterfallEndField: 'resolved_violations',
    },
    cacheSeconds: 3600,
  },

  // ─────────────────────────────────────────────────────────────
  // 20. Customer Satisfaction Scores – Bullet Chart
  // ─────────────────────────────────────────────────────────────
  {
    id: 'sys-rpt-020',
    name: 'Customer Satisfaction Scores',
    description: 'Bullet chart comparing actual CSAT score against target per service category.',
    dataSourceId: DEMO_SOURCE_ID,
    fields: [
      {
        id: 'f1',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'csat_surveys',
        columnName: 'category',
        label: 'Category',
        type: 'string',
        isDimension: true,
        isMeasure: false,
      },
      {
        id: 'f2',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'csat_surveys',
        columnName: 'score',
        label: 'Avg CSAT Score',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.0',
      },
      {
        id: 'f3',
        sourceId: DEMO_SOURCE_ID,
        tableName: 'csat_surveys',
        columnName: 'target_score',
        label: 'Target Score',
        type: 'number',
        isDimension: false,
        isMeasure: true,
        aggregation: 'avg',
        format: '0.0',
      },
    ],
    filters: [
      {
        id: 'flt1',
        fieldId: 'f_date',
        field: 'submitted_at',
        operator: 'gte',
        value: '{{__30d_ago}}',
        type: 'date',
        allowDashboardOverride: true,
        parameterName: 'date_from',
      },
    ],
    sorts: [{ fieldId: 'f2', field: 'score', direction: 'desc', priority: 1 }],
    chartConfig: {
      type: 'bar',
      xAxisField: 'category',
      yAxisFields: ['score'],
      referenceLines: [
        { value: 4.0, label: 'Target', color: '#22c55e', style: 'dashed' },
      ],
      showDataLabels: true,
      showLegend: true,
      targetField: 'target_score',
      gaugeBands: [
        { min: 0, max: 3, color: '#ef4444', label: 'Poor' },
        { min: 3, max: 4, color: '#f59e0b', label: 'Average' },
        { min: 4, max: 5, color: '#22c55e', label: 'Excellent' },
      ],
      colors: ['#7c3aed'],
    },
    cacheSeconds: 3600,
  },
]
